---

- name: Install audio packages
  pacman:
    state: present
    name:
      - pulseaudio
      - pulseaudio-alsa
      - pamixer
        #- ncpamixer # pulse audio ncurses mixer <- change to aur
      - pavucontrol
  tags:
    - audio
    - install_pacman

      #- name: Include JACK tasks
      #  include: jack.yml
      #  tags:
      #    - audio
