---

- name: Install audio packages
  pacman:
    state: present
    name:
      - pulseaudio
      - pulseaudio-alsa
      - pamixer
      - ncpamixer-git # pulse audio ncurses mixer
      - pavucontrol
  tags:
    - audio
    - install_pacman

- name: Include JACK tasks
  include: jack.yml
  tags:
    - audio
