---

- name: Install basic pacman packages
  pacman:
    state: present
    name:
      - deluge
      - curl
      - firefox
      - flameshot
      - gimp
      - git
      - guake
      - imagemagick
      - keepassxc
      - libreoffice-fresh
      - okular
      - pass
      - powerline
      - poppler-glib # open pdf in gimp
      - ranger
      - redshift
      - reflector
      - rxvt-unicode
      - samba
      - texlive-core
      - texlive-latexextra
      - tig
      - thunderbird
      - w3m # for ranger
      - wget
      - vim
      - vlc
  tags:
    - basic_packages
    - install_pacman

- name: Install basic aur packages
  aur:
    name: "{{ item }}"
    use: trizen
    skip_installed: true
  with_items:
    - advanced-ssh-config
    - arch-wiki-man # https://github.com/greg-js/arch-wiki-man
    - git-extras-git
    - gitflow-avh
    - dropbox
    - franz
    - gitlab-runner
    - google-chrome
    - homebank
    - jetbrains-toolbox
    - nixnote2
    - polybar
    - slack-desktop
    - spotify
    - qnapi
  tags:
    - basic_packages
    - install_aur
