#! /bin/bash
echo "Loading .xinitrc"

# set polish keyboard
setxkbmap pl

# run udiskie automounter for udisks2
udiskie --no-notify --tray --use-udisks2 &

# run redshift
pgrep redshift-gtk &> /dev/null || redshift-gtk &> /dev/null &

# run gnome-keyring
# based on: https://wiki.archlinux.org/index.php/GNOME/Keyring#xinitrc_method
dbus-update-activation-environment --systemd DISPLAY
eval "$(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)"
export SSH_AUTH_SOCK

# run clouds
/usr/bin/dropbox &
/usr/bin/pcloud &

## Run i3 with basic logging
# exec /usr/bin/i3 >~/i3log-$(date +'%F-%k-%M-%S') 2>&1
## Run i3 with extended logging
# exec /usr/bin/i3 -V -d all >~/i3log-$(date +'%F-%k-%M-%S') 2>&1
##  Run i3
exec i3
