---

- name: Install network packages
  pacman:
    state: present
    name:
      - networkmanager
      - network-manager-applet
      - gnome-keyring
      - seahorse
  tags:
    - network
    - install_pacman
