#!/bin/sh

# Must have jq, trans and xclip installed to even show menu.
jq -h > /dev/null || exit
trans -h > /dev/null || exit
xclip -h > /dev/null || exit

from_lang=$1
to_lang=$2

choice_word=$(rofi -dmenu -l 0 -p "Trans [$from_lang to $to_lang]")
# sed and awk based on: https://github.com/jonaburg/scripts/blob/master/translate
sentences=$(trans $from_lang:$to_lang "$choice_word" | sed -n '3p;4p' |awk -F1m '{print $2}' | sed -r 's/.....$//g')
if [ ! -z "$sentences" ]; then
    selected=$(echo -e $sentences | rofi -dmenu -i -p "Pick translation")
    if [ ! -z "$selected" ]; then
        echo $selected | xclip -selection clipboard
        notify-send "'$selected' copied to clipboard." &
    fi
fi

### trans -dump option has problem with jq, invalid json format
# json_dump=$(rofi -dmenu -l 0 -p "Trans [$from_lang to $to_lang]" | trans -dump $from_lang:$to_lang)
# echo $json_dump
# sentences=$(echo $json_dump | jq -r '.[5]')
# sentences=$(echo $json_dump | jq -r '.[5][0][2] | map(.[0]) | join("\\n")')


# todo below length options and if else could be used for fork words and sentences, because words can be grouped by (noun, etc)
#word_length=$(echo $json_dump | jq ".[1][0] | length")
#sentence_length=$(echo $json_dump | jq ".[5][0][2] | length")
#if [ $word_length != 0 ]; then
#    words=$(echo $json_dump | jq ".[1][0]")
#    echo $words
#    echo single
#else
#    sentences=$(echo $json_dump | jq ".[5][0][2]")
#    echo $sentences
#    echo multi
#fi






