#!/bin/sh
# Give dmenu list of all unicode characters to copy.
# Shows the selected character in dunst if running.

# Uses https://github.com/muan/emojilib library
# For update copy below file to the `dotfiles/home/config/emoji.json` path
# https://raw.githubusercontent.com/muan/emojilib/main/dist/emoji-en-US.json

# Must have below libs installed to even show menu
xclip -h > /dev/null || exit
jq -h > /dev/null || exit
xdotool -h > /dev/null || exit

EMOJI_FILE=$XDG_CONFIG_HOME/emoji.json
chosen=$(\
    jq < $EMOJI_FILE 'to_entries[] | .value|= join(", ") | .value |= split("_") | .value |= join(" ") | [.key, .value] | join(" - ")' -r \
    | rofi -dmenu -i -l 20 -p "Pick emoji"\
)

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo $c | xclip -r -selection clipboard
notify-send "'$c' copied to clipboard." &

## Dont know why this is in here, maybe vim primary regiser
# s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
# echo "$s" | tr -d '\n' | xclip
# notify-send "'$s' copied to primary." &

# Paste to the current text field
xdotool key "ctrl+shift+v"
