#!/bin/bash
#
# Set sensitivity for Lenovo Thinkpad inbuild keyboards 
# using: sudo ./trackpoint_set_sensitivity 250
#
# Resources:
# http://www.thinkwiki.org/wiki/How_to_configure_the_TrackPoint
# https://wiki.archlinux.org/index.php/TrackPoint
# https://gist.github.com/noromanba/11261595
#

SENSITIVITY=$1 # default 160
if [ -z "$SENSITIVITY" ]
then
    SENSITIVITY=250
    echo "First argument is empty, sensitivity will be set to ${SENSITIVITY}"
fi

echo ${SENSITIVITY} | tee /sys/devices/platform/i8042/serio1/serio2/speed
echo ${SENSITIVITY} | tee /sys/devices/platform/i8042/serio1/serio2/sensitivity

