---

- name: Install video pacman packages
  pacman:
    state: present
    name:
      - nvidia
      - nvidia-utils
      - opencl-nvidia
  tags:
    - video_packages
    - install_pacman

- name: Install video aur packages
  aur:
    name: "{{ item }}"
    use: yay
    state: present
  with_items:
    - davinci-resolve
  become: true
  become_user: aur_builder
  tags:
    - basic_packages
    - install_aur
