---

- name: Install python packages
  pacman:
    state: present
    name:
      - python-pip
      - python-virtualenv
      - python-virtualenvwrapper
      - python-pew
      - python-setuptools
      - twine
      - pyenv
  tags:
    - python
    - install_pacman

      #- name: Install aur python packages
      #  aur:
      #    name: "{{ item }}"
      #    use: yay
      #    state: present
      #  with_items:
      #  - pyenv-virtualenv
      #  tags:
      #    - python
      #    - install_aur
      #
