---

- name: Install pacman coding packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
  - python-pip
  - python-virtualenv
  - python-virtualenvwrapper
  - python-pew
  - python-pipenv

#- name: Install aur coding packages
#  aur:
#    name: "{{ item }}"
#    use: trizen
#    skip_installed: true
#  with_items:
#  -

