---

- name: Install docker packages.
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
  - docker
  - docker-compose

- name: Start docker service.
  systemd:
    name: docker.service
    state: started

- name: Create docker group.
  group:
    name: docker
    state: present

- name: Add docker group to user.
  user:
    name: "{{ localhost_user }}"
    groups: docker
    append: true

- name: Set .docker dir ownership and permissions.
  file:
    path: /home/{{ localhost_user }}/.docker
    owner: "{{ localhost_user }}"
    group: "{{ localhost_user }}"
    state: directory
    recurse: true
    force: true
