---

- name: Install postgresql package.
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
  - postgresql

- name: Install psycopg2 package.
  pip:
    name: psycopg2
    state: latest

- name: Create database cluster.
  command: sudo -iu postgres initdb -D '/var/lib/postgres/data'
  args:
    creates: /var/lib/postgres/data

- name: Start postgresql service.
  systemd:
    name: postgresql
    state: started

- name: Create base user
  postgresql_user:
    name: "{{ localhost_user }}"
    state: present
