---

- name: Install pacman coding packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
  - python-pip
  - python-virtualenv
  - python-virtualenvwrapper
  - python-pew
  - python-pipenv
  - rabbitmq
  - redis

- name: Start basic apps
  systemd:
    name: "{{ item }}"
    state: started
  with_items:
    - rabbitmq
    - redis

#- name: Install aur coding packages
#  aur:
#    name: "{{ item }}"
#    use: trizen
#    skip_installed: true
#  with_items:
#  -

