---

- name: Install pacman fonts
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
  - powerline-fonts

- name: Install aur fonts
  aur:
    name: "{{ item }}"
    use: trizen
    skip_installed: true
  with_items:
  - ttf-font-awesome
  - ttf-font-icons
  - ttf-inconsolata
  - ttf-lato
