---

- name: Update pacman cache
  pacman:
    update_cache: "{{ update_pacman_cache }}"

- name: Install basic pacman packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
  - firefox
  - guake
  - redshift
  - vlc
  - okular
  - gimp
  - libreoffice-fresh
  - deluge

- include_tasks: install_docker.yml
- include_tasks: install_udisks2.yml


