---
# based on: https://wiki.archlinux.org/index.php/udisks#Tips_and_tricks

- name: Install udisks2 package
  pacman:
    state: present
    name:
      - udisks2
      - udiskie
      # ntfs utils below
      - nfs-utils
      - ntfs-3g
  tags:
    - usb
    - install_pacman

- name: Create /media dir
  file:
    name: /media
    state: directory
    owner: root
    mode: 0755
  tags:
    - usb

- name: Add udev rule with mounting to /media conf file
  template:
    src: udisks2.rules
    dest: /etc/udev/rules.d/99-udisks2.rules
    owner: root
    mode: 0644
  tags:
    - usb
    - udev

- name: Create tempfiles.d snippet
  template:
    src: media.conf
    dest: /etc/tmpfiles.d/media.conf
    owner: root
    mode: 0644
  tags:
    - usb
