---

- name: Install pacman fonts
  pacman:
    state: present
    name:
      - powerline-fonts
      - noto-fonts-emoji
      - ttf-font-awesome
  tags:
    - fonts
    - install_pacman

- name: Install aur fonts
  aur:
    name: "{{ item }}"
    use: yay
    state: present
  with_items:
    - siji-git
    - ttf-font-icons
    - ttf-inconsolata
  become: true
  become_user: aur_builder
  tags:
    - fonts
    - install_aur
