---

- name: Install pacman fonts
  pacman:
    state: present
    name:
      - powerline-fonts
      - noto-fonts-emoji
  tags:
    - fonts
    - install_pacman

- name: Install aur fonts
  aur:
    name: "{{ item }}"
    use: trizen
    skip_installed: true
  become: yes
  become_user: aur_builder
  with_items:
    - siji-git
#    - ttf-font-awesome
#    - ttf-font-icons
#    - ttf-inconsolata
  tags:
    - fonts
    - install_aur
