---

- name: Install basic pacman packages
  pacman:
    state: present
    name:
      - arandr # xrandr gui (screens)
      - aws-cli
      - curl
      - code
      - calibre
      - deluge
      - deluge-gtk
      - discord
      - dunst
      - exa # modern ls
      - electrum
      - ffmpeg
      - firefox
      - flameshot
      - gimp
      - git
      - htop
      - xorg-xinit # i3 need it
      - i3-gaps
      - i3lock
      - gwenview
      - gvfs # thunar need it
      - imagemagick
      - inkscape
      - jq # json parser
      - keepassxc
      # - kazam
      - kubectl
      - libreoffice-fresh
      - neovim
      - obs-studio
      - okular
      - ntp # time sync
      - pass
      - polkit # allow unprivileged users to run power management commands
      - powerline
      - poppler-glib # open pdf in gimp
      - prusa-slicer
      - ranger
      - redshift
      - reflector
      - rxvt-unicode
      - samba
      - sxhkd # hotkeys daemon
      - texlive-core
      - texlive-latexextra
      - thunar # file manager
      - thunar-volman # file manager
      - translate-shell
      - tig
      - tilda
      - thunderbird
      - w3m # for ranger
      - imlib2 # for w3m
      - wget
      - whois
      - vim
      - vlc
      - xclip # clipboard utility
      # - zeal # documentation utility
  tags:
    - basic_packages
    - install_pacman

- name: Install basic aur packages
  aur:
    name: "{{ item }}"
    use: yay
    state: present
  with_items:
    - advanced-ssh-config
    - aws-okta-bin
    # - arch-wiki-man # https://github.com/greg-js/arch-wiki-man
    - dropbox
    # - franz
    - freecad-appimage-git
    - git-extras-git
    # - gitflow-avh
    # - gitlab-runner
    - google-chrome
    # - homebank
    # - insomnia # https://github.com/getinsomnia/insomnia
    # - jetbrains-toolbox
    - nixnote2-git
    - polybar
    - phantomjs # for youtube-dlc
    - slack-desktop
    - spotify
    - todoist-git
    - tfenv
    - qnapi
    - youtube-dlc
    - zoom
  become: true
  become_user: aur_builder
  tags:
    - basic_packages
    - install_aur


- name: Install basic python packages
  pip:
    state: present
    name:
      # - dmenu-hotkeys
      - glances
      # - spotdl
  tags:
    - basic_packages
    - install_pip
