---

- name: Install basic pacman packages
  pacman:
    state: present
    name:
      - arandr # xrandr gui (screens)
      - curl
      - deluge
      - dunst
      - exa # modern ls
      - ffmpeg
      - firefox
      - flameshot
      - gimp
      - git
      - gwenview
      - imagemagick
      - jq # json parser
      - keepassxc
      - libreoffice-fresh
      - okular
      - pass
      - polkit # allow unprivileged users to run power management commands
      - powerline
      - poppler-glib # open pdf in gimp
      - ranger
      - redshift
      - reflector
      - rxvt-unicode
      - samba
      - texlive-core
      - texlive-latexextra
      - tig
      - tilda
      - thunderbird
      - w3m # for ranger
      - wget
      - vim
      - vlc
      - xclip # clipboard utility
  tags:
    - basic_packages
    - install_pacman

- name: Install basic aur packages
  aur:
    name: "{{ item }}"
    use: trizen
    skip_installed: true
  with_items:
    - advanced-ssh-config
    - arch-wiki-man # https://github.com/greg-js/arch-wiki-man
    - dropbox
    - franz
    - git-extras-git
    - gitflow-avh
    - gitlab-runner
    - google-chrome
    - homebank
    - insomnia # https://github.com/getinsomnia/insomnia
    - jetbrains-toolbox
    - nixnote2
    - polybar
    - phantomjs # for youtube-dl
    - slack-desktop
    - spotify
    - qnapi
    - youtube-dl
  tags:
    - basic_packages
    - install_aur


- name: Install basic python packages
  pacman:
    state: present
    name:
      - glances
      - spotdl
  tags:
    - basic_packages
    - install_pip
